### ISSUE TITLE
Added reproduction data and code

### ISSUE THREAD

**Issue by Starlitnightly** [Starlitnightly/omicverse-reproducibility#2]
@DBinary 

Please add code and data for Fig3, sfig5/6.
- Code needs to be in `docs` folder
- Data needs to be put in data folder, if the data file is too big, then you need to store it in public disc or contact ZehuaZeng to store it in figshare.

And need to update `mkdocs.yml` and `readme.md` accordingly.

**Comment by DBinary** [comment]
Hi Zehua,

The code for Fig3, sfig5/6 has been updated at #3 

The data for Fig3, sfig5/6 will be sent to you soon.
